update from upstream

diff --git a/root/usr/bin/vssr-switch b/root/usr/bin/vssr-switch
--- a/root/usr/bin/vssr-switch
+++ b/root/usr/bin/vssr-switch
@@ -34,68 +34,70 @@ CURRENT_SERVER=$DEFAULT_SERVER
 
 #判断代理是否正常
 check_proxy() {
-    local result=0
-    local try_count=$(uci_get_by_type global switch_try_count 3)
-    for i in $(seq 1 $try_count); do
-        /usr/bin/ssr-check www.google.com 80 $switch_time 1
-        if [ "$?" == "0" ]; then
-            result=0
-            break
-        else
-            /usr/bin/ssr-check www.baidu.com 80 $switch_time 1
-            if [ "$?" == "0" ]; then
-                result=1
-            else
-                result=2
-            fi
-        fi
-        sleep 1
-    done
-    return $result
+  local result=0
+  local try_count=$(uci_get_by_type global switch_try_count 3)
+  for i in $(seq 1 $try_count); do
+    /usr/bin/vssr-check www.google.com 443 $switch_time 1
+    if [ "$?" == "0" ]; then
+      # echo "$(date "+%Y-%m-%d %H:%M:%S") Check Google Proxy Success, count=$i" >> /tmp/ssrplus.log
+      result=0
+      break
+    else
+      # echo "$(date "+%Y-%m-%d %H:%M:%S") Check Google Proxy Fail, count=$i" >> /tmp/ssrplus.log
+      /usr/bin/vssr-check www.baidu.com 443 $switch_time 1
+      if [ "$?" == "0" ]; then
+        result=1
+      else
+        result=2
+      fi
+    fi
+    sleep 1
+  done
+  return $result
 }
 
 test_proxy() {
-    local servername=$(uci_get_by_name $1 server)
-    local serverport=$(uci_get_by_name $1 server_port)
-    ret=$(ping -c 3 $servername | grep 'loss' | awk -F ',' '{ print $3 }' | awk -F "%" '{ print $1 }')
-    [ -z "$ret" ] && return 1
-    [ "$ret" -gt "50" ] && return 1
-    ipset add ss_spec_wan_ac $servername 2>/dev/null
-    ret=$?
-    /usr/bin/ssr-check $servername $serverport $switch_time
-    local ret2=$?
-    if [ "$ret" = "0" ]; then
-        ipset del ss_spec_wan_ac $servername 2>/dev/null
-    fi
-    if [ "$ret2" = "0" ]; then
-        return 0
-    else
-        return 1
-    fi
+  local servername=$(uci_get_by_name $1 server)
+  local serverport=$(uci_get_by_name $1 server_port)
+  ret=$(ping -c 3 $servername | grep 'loss' | awk -F ',' '{ print $3 }' | awk -F "%" '{ print $1 }')
+  [ -z "$ret" ] && return 1
+  [ "$ret" -gt "50" ] && return 1
+  ipset add ss_spec_wan_ac $servername 2>/dev/null
+  ret=$?
+  /usr/bin/vssr-check $servername $serverport $switch_time
+  local ret2=$?
+  if [ "$ret" = "0" ]; then
+    ipset del ss_spec_wan_ac $servername 2>/dev/null
+  fi
+  if [ "$ret2" = "0" ]; then
+    return 0
+  else
+    return 1
+  fi
 }
 
 search_proxy() {
-    let server_count=server_count+1
-    [ "$normal_flag" = "1" -a "$server_count" -le "$server_locate" ] && return 0
-    [ "$(uci_get_by_name $1 switch_enable)" != "1" ] && return 1
-    [ $ENABLE_SERVER != nil ] && return 0
-    [ "$1" = "$CURRENT_SERVER" ] && return 0
-    local servername=$(uci_get_by_name $1 server)
-    local serverport=$(uci_get_by_name $1 server_port)
-    ipset add ss_spec_wan_ac $servername 2>/dev/null
-    ret=$?
-    /usr/bin/ssr-check $servername $serverport $switch_time
-    local ret2=$?
-    if [ "$ret" = "0" ]; then
-        ipset del ss_spec_wan_ac $servername 2>/dev/null
-    fi
-    if [ "$ret2" = "0" ]; then
-        server_locate=$server_count
-        ENABLE_SERVER=$1
-        return 0
-    else
-        return 1
-    fi
+  let server_count=server_count+1
+  [ "$normal_flag" = "1" -a "$server_count" -le "$server_locate" ] && return 0
+  [ "$(uci_get_by_name $1 switch_enable)" != "1" ] && return 1
+  [ $ENABLE_SERVER != nil ] && return 0
+  [ "$1" = "$CURRENT_SERVER" ] && return 0
+  local servername=$(uci_get_by_name $1 server)
+  local serverport=$(uci_get_by_name $1 server_port)
+  ipset add ss_spec_wan_ac $servername 2>/dev/null
+  ret=$?
+  /usr/bin/vssr-check $servername $serverport $switch_time
+  local ret2=$?
+  if [ "$ret" = "0" ]; then
+    ipset del ss_spec_wan_ac $servername 2>/dev/null
+  fi
+  if [ "$ret2" = "0" ]; then
+    server_locate=$server_count
+    ENABLE_SERVER=$1
+    return 0
+  else
+    return 1
+  fi
 
 }
 #选择可用的代理
@@ -116,36 +118,42 @@ switch_proxy() {
 }
 
 start() {
-    #不支持kcptun启用时的切换
-    [ $(uci_get_by_name $DEFAULT_SERVER kcp_enable) = "1" ] && return 1
+  #不支持kcptun启用时的切换
+  [ $(uci_get_by_name $DEFAULT_SERVER kcp_enable) = "1" ] && return 1
+  local auto_restart=$(uci_get_by_type global enable_restart '0')
 
-    while [ "1" = "1" ]; do #死循环
-        sleep $cycle_time
+  while [ "1" = "1" ]; do #死循环
+    sleep $cycle_time
 
-        LOGTIME=$(date "+%Y-%m-%d %H:%M:%S")
+    LOGTIME=$(date "+%Y-%m-%d %H:%M:%S")
 
-        #判断当前代理是否为缺省服务器
-        if [ "$CURRENT_SERVER" != "$DEFAULT_SERVER" ]; then
-            #echo "not default proxy"
-            echo "$(date "+%Y-%m-%d %H:%M:%S") 当前为备用节点，尝试切换为主节点。" >>/tmp/vssr.log
+    #判断当前代理是否为缺省服务器
+    if [ "$CURRENT_SERVER" != "$DEFAULT_SERVER" ]; then
+      #echo "not default proxy"
+      echo "$(date "+%Y-%m-%d %H:%M:%S") 当前为备用节点，尝试切换为主节点。" >>/tmp/vssr.log
 
-            #检查缺省服务器是否正常
-            if test_proxy $DEFAULT_SERVER; then
-                #echo "switch to default proxy"
-                echo "$(date "+%Y-%m-%d %H:%M:%S") 主节点不可用." >>/tmp/vssr.log
-                #缺省服务器正常，切换回来
-                CURRENT_SERVER=$DEFAULT_SERVER
-                switch_proxy $CURRENT_SERVER
-                echo "$(date "+%Y-%m-%d %H:%M:%S") 切换为默认节点 ["$(uci_get_by_name $CURRENT_SERVER server)"]" >>/tmp/vssr.log
-                continue
-            else
-                echo "$(date "+%Y-%m-%d %H:%M:%S") 主节点不可用，继续使用当前备用节点。" >>/tmp/vssr.log
-            fi
-        fi
+      #检查缺省服务器是否正常
+      if test_proxy $DEFAULT_SERVER; then
+        #echo "switch to default proxy"
+        echo "$(date "+%Y-%m-%d %H:%M:%S") 主节点不可用." >>/tmp/vssr.log
+        #缺省服务器正常，切换回来
+        CURRENT_SERVER=$DEFAULT_SERVER
+        switch_proxy $CURRENT_SERVER
+        echo "$(date "+%Y-%m-%d %H:%M:%S") 切换为默认节点 ["$(uci_get_by_name $CURRENT_SERVER server)"]" >>/tmp/vssr.log
+        continue
+      else
+        echo "$(date "+%Y-%m-%d %H:%M:%S") 主节点不可用，继续使用当前备用节点。" >>/tmp/vssr.log
+      fi
+    fi
 
-        #判断当前代理是否正常
-        check_proxy
-        current_ret=$?
+    #判断当前代理是否正常
+    check_proxy
+    current_ret=$?
+    if [ "$current_ret" = "1" ] && [ "$auto_restart" = "1" ]; then
+      echo "$(date "+%Y-%m-%d %H:%M:%S") 主节点不可用，尝试重启." >>/tmp/vssr.log
+      /etc/init.d/vssr restart
+      continue
+    fi
 
         if [ "$current_ret" = "1" ]; then
             #当前代理错误，判断有无可用的服务器
@@ -170,6 +178,6 @@ start() {
             #echo "$(date "+%Y-%m-%d %H:%M:%S") vssr No Problem."  >> /tmp/vssr.log
         fi
 
-    done
+  done
 
 }
